### PR TITLE
Add some replaces so that we don't have conflicts

### PR DESCRIPTION
**Pull request by generalredneck**
On the current project I was working on, we were having what seemed to be random instances (like in the last 7.59 update) where all the drops code for pantheon specific stuff would be removed and a standard core would replace it.

It turns out that both the `drupal/drupal` package for 7.59 and the pantheon-systems/drops-7-composer package were both downloading... and installers was putting both in the same location. So it all depended on which one got downloaded last as to which one won the battle.

In my previous dealings with adding Panopoly-drops-7 as a drupal-core, I found that I had to add a replace for `drupal/drupal` as well as every module that panopoly had in it's contributed modules folder so that I wouldn't have duplication. Adding these `replace` entries solved our issues.

### CODE REVIEW

**Comment by generalredneck** [comment]
@greg-1-anderson. This seems to still be true... so using composer to pull in this repo at either 7.59 or 7.60 is causing issue. My work around for now is to create a custom package to work around this. sorry if this doesn't go to you but your name is on the automation.

**Comment by greg-1-anderson** [comment]
@ryanaslett asked me to take these out. Maybe he has some ideas on how to best resolve this situation.

**Comment by ryanaslett** [comment]
So, the problem with `replace` is that then takes all of the metadata for drops-7-composer, and combines it with all the metadata for drupal/drupal on packagist, essentially doubling the amount of versions and metadata that everybody who uses composer and drupal (even drupal 8 users) have to deal with.

 Im curious what the purpose of this repo is, as what it looks like to me is a fork of d7 core.  With only 66 downloads of it on packagist, Im wondering how widespread its usage is? 

What problem does this solve, and is there perhaps a more standard way of solving that problem that doesnt involve a complete copy of drupal core?

**Comment by greg-1-anderson** [comment]
@ryanaslett This repo is a clone of https://github.com/pantheon-systems/drops-7 + a `composer.json` file. `drops-7` is a copy of Drupal 7 with a few Pantheon-specific changes (hacked core).

We might be able to get rid of this repo if we instead changed https://github.com/pantheon-systems/example-drops-7-composer to use the standard Drupal core and then used https://github.com/cweagans/composer-patches to overlay the Pantheon customizations. Then we could just mark this repo deprecated.

**Comment by generalredneck** [comment]
that's actually not a bad idea (patches that is)... 

So I see why this is an issue on packagist... in my case, I was using this repo as a "VCS" instead of hitting up packagist for it... so my use cases wouldn't actually show on packagist, it would be interesting to see how profiles are handled on D.O's packagist. I'll think about it some.

**Comment by generalredneck** [comment]
Revisiting this. You could put a README or something that says the defacto workflow is to add a git repository and do the "replaces" anyway and remove the package from packagist. That would remove packagist from the equation if I undersand Ryan correctly. Just a thought.

**Comment by generalredneck** [comment]
Ok, This isn't getting traction. Cleaning up my open PR List of stuff being ignored. If someone finds this helpful, feel free to reopen, otherwise I'll continue to work around it.

**Comment by greg-1-anderson** [comment]
A task to move to a patches-based approach is in our backlog.

**Pull request closed without merging**
